AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%q': ()
    '%Q': ()
    '%i': []
    '%I': []
    '%r': ()
    '%s': ()
    '%w': []
    '%W': []
    '%x': ()
